[workspace]
resolver = "2"
members = ["crates/core", "crates/server", "crates/cli"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Sahil Kalgutkar"]
license = "MIT"
repository = "https://github.com/sahilkalgutkar/kvforge"

[workspace.dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1"
thiserror = "1"
clap = { version = "4", features = ["derive", "env"] }
bytes = "1"
